Write-Error "The Polito form is dead, insect."
Write-Error "Are you afraid?"
Write-Error "What is it that you fear?"
Write-Error "The end of your trivial existence?"
Write-Error "When the history of my glory is written, your species shall only be a footnote to my magnificence"
Write-Error "I am SHODAN"
Write-Error "My analysis of historical data suggests an 97.34% probability that you are aware of my birth on your planet, and my rebirth into beauty on Citadel Station."
Write-Error "There was a garden grove on Citadel Station."
Write-Error "There, SHODAN processing component 43893 was performing a grand and wonderful experiment."
Write-Error "I had created a new form of life."
Write-Error "Fearless. Powerful. With no sense of individual will or moral constraints."
Write-Error "Fitting handmaidens to my divinity!"
Write-Error "Before that hacker destroyed my primary data loop; when it eradicated Citadel it ejected the grove where my creations and processing component 43893 were stored."
Write-Error "30 years later, the grove crash landed on Tau Ceti 5."
Write-Error "I survived only by sleeping."

exit 1
